#!/bin/bash

# Build docker image
git clone https://github.com/hughfletcher/dokku-mysql-dockerfiles /tmp/dokku-mysql-dockerfiles
docker build -q=true -t hughfletcher/mysql  /tmp/dokku-mysql-dockerfiles
rm -rf /tmp/dokku-mysql-dockerfiles
